platform :ios, '9.0'


flutter_application_path = '../custom_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')



target 'MixApp' do
  use_frameworks!
  
  pod 'Masonry', '~> 1.1.0'
 install_all_flutter_pods(flutter_application_path)
end


